import * as React from "react";
import Head from "next/head";
import AdmissionBg from "../components/MainComponents/AdmissionBg";
import BelowAdmissionBg from "../components/MainComponents/BelowAdmissionBg";
import WhyComponents from "../components/MainComponents/WhyComponents";
import Moto from "../components/MainComponents/Moto";
import BelowMoto from "../components/MainComponents/BelowMoto";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shalom International School & Jr. College</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AdmissionBg />
      <BelowAdmissionBg />
      <WhyComponents />
      <Moto />
      <BelowMoto />

      
      {/* <Container sx={{ height: "100%", width: "100%", margin: "2rem auto" }}>
        <Typography variant="h4" sx={{ textAlign: "center", margin: "3rem 0" }}>
          {main.ch}
        </Typography>
        <Box sx={{ width: "100%" }}>
          <Carousel breakpoints={breakPoints}>
            <CustomCard>1</CustomCard>
            <CustomCard>1</CustomCard>
            <CustomCard>1</CustomCard>
            <CustomCard>1</CustomCard>
            <CustomCard>1</CustomCard>
          </Carousel>
        </Box>
      </Container>
      <Box
        sx={{
          position: "relative",
          width: "100%",
          height: "100%",
        }}
        disabled
      >
        <iframe
          style={{
            position: "relative",
            top: 0,
            left: 0,
            width: "640",
            // height: "50%",
          }}
          src={
            "https://www.youtube.com/embed/XaXgLtnoKUE?controls=0&rel=0&playsinline=1&enablejsapi=1&origin=https%3A%2F%2Fwww.shalominternationalschool.com&widgetid=3"
          }
          title="YouTube video player"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture;web-share"
          allowFullScreen
          frameborder="0"
          autoplay="1"
          mute="1"
        />
      </Box> */}
    </>
  );
}
