import * as React from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
import { main } from "../utils/text_utils/textUtils";
import Typography from "@mui/material/Typography";
import { breakpoints, display, positions } from "@mui/system";
import Button from "@mui/material/Button";
import { styled } from "@mui/material/styles";
import ImageListItem from "@mui/material/ImageListItem";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import { CardActionArea, CardActions } from "@mui/material";
import LanguageIcon from "@mui/icons-material/Language";
import FontDownloadIcon from "@mui/icons-material/FontDownload";
import LaptopIcon from "@mui/icons-material/Laptop";
import BookIcon from "@mui/icons-material/Book";
import SportsSoccerIcon from "@mui/icons-material/SportsSoccer";
import ChangeHistoryIcon from "@mui/icons-material/ChangeHistory";
import ListItemText from "@mui/material/ListItemText";
import ListItem from "@mui/material/ListItem";
import Grid from "@mui/material/Grid";
import ReactDom from "react-dom";
import Carousel from "react-elastic-carousel";

const CustomCard = styled(Box)`
  display: flex;
  justify-content: center;
  align-items: center;
  height: 250px;
  width: 20%;
  background-color: #683bb7;
  color: #fff;
  margin: 15px;
  font-size: 4em;
`;

const Typo = styled("Typography")(({ theme }) => ({
  [theme.breakpoints.down("md")]: {
    width: "100%",
    height: "100vh",
    flexWrap: "wrap",
    textAlign: "center",
    paddingTop: "5rem",
  },
  [theme.breakpoints.up("md")]: {
    width: "100%",
    flexWrap: "wrap",
    textAlign: "center",
  },
  [theme.breakpoints.up("lg")]: {
    width: "55%",
    flexWrap: "nowrap",
  },
}));
const BoxBtn1 = styled("Box")(({ theme }) => ({
  [theme.breakpoints.down("md")]: {
    flexDirection: "column",
  },
  [theme.breakpoints.up("md")]: {
    flexDirection: "column",
  },
  [theme.breakpoints.up("lg")]: {
    flexDirection: "row",
  },
}));
const BoxBtn2 = styled("Box")(({ theme }) => ({
  [theme.breakpoints.down("md")]: {
    width: "100%",
  },
  [theme.breakpoints.up("md")]: {
    width: "100%",
  },
  [theme.breakpoints.up("lg")]: {
    width: "55%",
  },
}));
const BoxBtn3 = styled("Box")(({ theme }) => ({
  [theme.breakpoints.down("md")]: {
    width: "100%",
  },
  [theme.breakpoints.up("md")]: {
    width: "100%",
  },
  [theme.breakpoints.up("lg")]: {
    width: "35%",
  },
}));
const BoxBtn4 = styled("Box")(({ theme }) => ({
  [theme.breakpoints.down("md")]: {
    height: "100%",
    flexDirection: "column",
  },
  [theme.breakpoints.up("md")]: {
    height: "100%",
    flexDirection: "column",
  },
  [theme.breakpoints.up("lg")]: {
    height: "40vh",
    flexDirection: "row",
  },
}));
const Cont1 = styled("Container")(({ theme }) => ({
  [theme.breakpoints.down("md")]: {
    height: "100%",
  },
  [theme.breakpoints.up("md")]: {
    height: "100%",
  },
  [theme.breakpoints.up("lg")]: {
    height: "25vh",
  },
}));
const Cont2 = styled("Container")(({ theme }) => ({
  [theme.breakpoints.down("md")]: {
    flexDirection: "column",
    width: "100%",
  },
  [theme.breakpoints.up("md")]: {
    flexDirection: "column",
    width: "100%",
  },
  [theme.breakpoints.up("lg")]: {
    flexDirection: "row",
    width: "55%",
  },
}));
const ILTem = styled("ImageListItem")(({ theme }) => ({
  [theme.breakpoints.down("md")]: {
    width: 300,
    height: 450,
    transform: "translateZ(0)",
  },
  [theme.breakpoints.up("md")]: {
    width: 500,
    height: 350,
    transform: "translateZ(0)",
  },
}));
const breakPoints = [
  { width: 1, itemToShow: 3 },
  { width: 550, itemToShow: 2 },
  { width: 760, itemToShow: 3 },
  { width: 1200, itemToShow: 4 },
];
export default function Home() {
  return (
    <>
      <Head>
        <title>Shalom International School & Jr. College</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box maxWidth="false" className={styles.main}>
        <Box
          sx={{
            display: "flex",
            justifyContent: "flex-end",
            alignItems: "center",
            flexDirection: "column",
            width: "100%",
            margin: "auto",
            height: "95vh",
            textAlign: "center",
            color: "white",
            paddingBottom: "3rem",
            backgroundPosition: "center",
            backgroundSize: "cover",
            background: "rgba(0, 0, 0, 0.6)",
          }}
        >
          <Typo>
            <Typography
              variant="h4"
              gutterBottom
              sx={{
                fontWeight: "700",
              }}
            >
              {main.Add}
            </Typography>
            <Typography variant="body1" gutterBottom>
              {main.Det}
            </Typography>

            <BoxBtn1 sx={{ display: "flex", width: "100%" }}>
              <BoxBtn2
                sx={{
                  display: "flex",
                  justifyContent: "flex-end",
                }}
              >
                <BoxBtn3
                  variant="contained"
                  sx={{
                    borderRadius: "3rem",
                    padding: "1rem",
                    margin: ".5rem",
                    textDecoration: "underline",
                    border: "2px solid white",
                    background: "#720404F2",
                    "&:hover": { backgroundColor: "#720404F2" },
                  }}
                >
                  {main.btn1}
                </BoxBtn3>
              </BoxBtn2>
              <BoxBtn2
                sx={{
                  display: "flex",
                  width: "50%",
                  justifyContent: "flex-start",
                }}
              >
                <BoxBtn3
                  variant="outlined"
                  sx={{
                    width: "30%",
                    borderRadius: "3rem",
                    padding: "1rem",
                    margin: ".5rem",
                    color: "white",
                    border: "2px solid white",
                    textDecoration: "underline",
                  }}
                >
                  {main.btn2}
                </BoxBtn3>
              </BoxBtn2>
            </BoxBtn1>
          </Typo>
        </Box>
      </Box>
      <Box maxWidth="false" className={styles.main2}>
        <BoxBtn4
          sx={{
            display: "flex",
            justifyContent: "flex-start",
            alignItems: "center",
            width: "100%",
            color: "black",
          }}
        >
          <ILTem
            sx={{
              display: "flex",
              justifyContent: "flex-start",
              alignItems: "center",
            }}
          >
            <img src={main.img} loading="lazy" />
          </ILTem>
          <Box sx={{ width: "70%", margin: "4rem" }}>
            <Typography
              variant="h5"
              gutterBottom
              sx={{
                fontWeight: "700",
                color: "#720404F2",
                textAlign: "start",
              }}
            >
              {main.h1}
            </Typography>
            <Typography variant="body1" gutterBottom>
              {main.h1B}
            </Typography>
          </Box>
        </BoxBtn4>
      </Box>
      <Box>
        <Container
          maxWidth="lg"
          sx={{
            display: "flex",
            flexWrap: "wrap",
            alignItem: "center",
            justifyContent: "center",
            marginBottom: "3rem",
          }}
        >
          <Typography
            variant="h4"
            gutterBottom
            sx={{
              textAlign: "center",
              fontWeight: "700",
              color: "#720404F2",
            }}
          >
            {main.q}
          </Typography>
          <Card sx={{ maxWidth: 345, margin: "1rem", boxShadow: "none" }}>
            <CardActionArea sx={{ display: "flex", alignItems: "flex-start" }}>
              <LanguageIcon sx={{ fontSize: "3rem", color: "#720404F2" }} />
              <CardContent>
                <Typography gutterBottom variant="h5" component="div">
                  {main.c1h}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {main.c1b}
                </Typography>
              </CardContent>
            </CardActionArea>
          </Card>
          <Card sx={{ maxWidth: 345, margin: "1rem", boxShadow: "none" }}>
            <CardActionArea sx={{ display: "flex", alignItems: "flex-start" }}>
              <FontDownloadIcon sx={{ fontSize: "3rem", color: "#720404F2" }} />
              <CardContent>
                <Typography gutterBottom variant="h5" component="div">
                  {main.c2h}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {main.c2b}
                </Typography>
              </CardContent>
            </CardActionArea>
          </Card>
          <Card sx={{ maxWidth: 345, margin: "1rem", boxShadow: "none" }}>
            <CardActionArea sx={{ display: "flex", alignItems: "flex-start" }}>
              <LaptopIcon sx={{ fontSize: "3rem", color: "#720404F2" }} />
              <CardContent>
                <Typography gutterBottom variant="h5" component="div">
                  {main.c3h}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {main.c3b}
                </Typography>
              </CardContent>
            </CardActionArea>
          </Card>
          <Card sx={{ maxWidth: 345, margin: "1rem", boxShadow: "none" }}>
            <CardActionArea sx={{ display: "flex", alignItems: "flex-start" }}>
              <BookIcon sx={{ fontSize: "3rem", color: "#720404F2" }} />
              <CardContent>
                <Typography gutterBottom variant="h5" component="div">
                  {main.c4h}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {main.c4b}
                </Typography>
              </CardContent>
            </CardActionArea>
          </Card>
          <Card sx={{ maxWidth: 345, margin: "1rem", boxShadow: "none" }}>
            <CardActionArea sx={{ display: "flex", alignItems: "flex-start" }}>
              <SportsSoccerIcon sx={{ fontSize: "3rem", color: "#720404F2" }} />
              <CardContent>
                <Typography gutterBottom variant="h5" component="div">
                  {main.c5h}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {main.c5b}
                </Typography>
              </CardContent>
            </CardActionArea>
          </Card>
          <Card sx={{ maxWidth: 345, margin: "1rem", boxShadow: "none" }}>
            <CardActionArea sx={{ display: "flex", alignItems: "flex-start" }}>
              <ChangeHistoryIcon
                sx={{ fontSize: "3rem", color: "#720404F2" }}
              />
              <CardContent>
                <Typography gutterBottom variant="h5" component="div">
                  {main.c6h}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {main.c6b}
                </Typography>
              </CardContent>
            </CardActionArea>
          </Card>
        </Container>
      </Box>

      
      <Cont2
        sx={{
          display: "flex",
          alignItem: "center",
          justifyContent: "center",
          letterSpacing: "-0.15px",
          width: "55%",
          margin: "auto",
        }}
      >
        <BoxBtn2
          sx={{ width: "50%", alignItem: "center", alignContent: "center" }}
        >
          <ListItem sx={{ width: "100%" }}>
            <Typography
              gutterBottom
              variant="h5"
              component="div"
              sx={{
                color: "#720404F2",
                textAlign: "right",
                width: "50%",
                padding: "15px",
                fontSize: "45px",
                fontWeight: "500",
              }}
            >
              {main.m1h}
            </Typography>
            <ListItemText
              primary={main.m1b}
              sx={{
                color: "black",
                fontWeight: "400",
                width: "50%",
                padding: "15px",
                fontSize: "20px",
              }}
            />
          </ListItem>
          <ListItem sx={{ width: "100%" }}>
            <Typography
              gutterBottom
              variant="h5"
              component="div"
              sx={{
                color: "#720404F2",
                textAlign: "right",
                width: "50%",
                padding: "15px",
                fontSize: "45px",
                fontWeight: "500",
              }}
            >
              {main.m2h}
            </Typography>
            <ListItemText
              primary={main.m2b}
              sx={{
                color: "black",
                fontWeight: "400",
                width: "50%",
                padding: "15px",
                fontSize: "20px",
              }}
            />
          </ListItem>
          <ListItem sx={{ width: "100%" }}>
            <Typography
              gutterBottom
              variant="h5"
              component="div"
              sx={{
                color: "#720404F2",
                textAlign: "right",
                width: "50%",
                padding: "15px",
                fontSize: "45px",
                fontWeight: "500",
              }}
            >
              {main.m3h}
            </Typography>
            <ListItemText
              primary={main.m3b}
              sx={{
                color: "black",
                fontWeight: "400",
                width: "50%",
                padding: "15px",
                fontSize: "20px",
              }}
            />
          </ListItem>
          <ListItem sx={{ width: "100%" }}>
            <Typography
              gutterBottom
              variant="h5"
              component="div"
              sx={{
                color: "#720404F2",
                textAlign: "right",
                width: "50%",
                padding: "15px",
                fontSize: "45px",
                fontWeight: "500",
              }}
            >
              {main.m4h}
            </Typography>
            <ListItemText
              primary={main.m4b}
              sx={{
                color: "black",
                fontWeight: "400",
                width: "50%",
                padding: "15px",
                fontSize: "20px",
              }}
            />
          </ListItem>
        </BoxBtn2>
        <BoxBtn2
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            width: "50%",
          }}
        >
          <ListItem
            sx={{
              flexDirection: "column",
              alignItems: "center",
              alignContent: "center",
              width: "100%",
            }}
          >
            <Typography
              gutterBottom
              variant="h5"
              component="div"
              sx={{ color: "#720404F2", fontWeight: "700", fontSize: "30px" }}
            >
              {main.mh}
            </Typography>
            <ListItemText
              primary={main.mb}
              sx={{ fontWeight: "400", fontSize: "20px", lineHeight: "1.4em" }}
            />
          </ListItem>
        </BoxBtn2>
      </Cont2>
      <Cont1
        maxWidth="false"
        sx={{
          height: "20vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          textAlign: "center",
          background: "#720404F2",
          color: "white",
        }}
      >
        <Typography variant="h4">{main.ah}</Typography>
        <Typography variant="body1" sx={{ width: "60%" }}>
          {main.ab}
        </Typography>
      </Cont1>
      {/* <Container sx={{ height: "100%", width: "100%", margin: "2rem auto" }}>
        <Typography variant="h4" sx={{ textAlign: "center", margin: "3rem 0" }}>
          {main.ch}
        </Typography>
        <Box sx={{ width: "100%" }}>
          <Carousel breakpoints={breakPoints}>
            <CustomCard>1</CustomCard>
            <CustomCard>1</CustomCard>
            <CustomCard>1</CustomCard>
            <CustomCard>1</CustomCard>
            <CustomCard>1</CustomCard>
          </Carousel>
        </Box>
      </Container>
      <Box
        sx={{
          position: "relative",
          width: "100%",
          height: "100%",
        }}
        disabled
      >
        <iframe
          style={{
            position: "relative",
            top: 0,
            left: 0,
            width: "640",
            // height: "50%",
          }}
          src={
            "https://www.youtube.com/embed/XaXgLtnoKUE?controls=0&rel=0&playsinline=1&enablejsapi=1&origin=https%3A%2F%2Fwww.shalominternationalschool.com&widgetid=3"
          }
          title="YouTube video player"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture;web-share"
          allowFullScreen
          frameborder="0"
          autoplay="1"
          mute="1"
        />
      </Box> */}
    </>
  );
}
